name: nasapic
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  dartz: ^0.10.1
  get_it: ^7.6.4
  injectable: ^2.3.2
  dio: ^5.4.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^5.0.2
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  auto_size_text: ^3.0.0
  shimmer: ^3.0.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  injectable_generator: ^2.4.1
  mockito: ^5.4.3
  hive_generator: ^2.0.1
  bloc_test: ^9.1.5

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - .env
